name: Fourteenth Workflow
on: workflow_dispatch
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Cache node_modules
              id: cache-step
              uses: actions/cache@v5
              with:
                path: ~/.npm
                key: "cache-file"
            - name: Display Cache
              run: echo '${{ steps.cache-step.outputs }}'
            - name: Install node_modules
              run: npm install
            