name: Fourth Workflow

on:
  workflow_run:
    workflows: ["Third Workflow"]
    types:
      - completed

jobs:
    succes-command:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - name: List Files
              run: |
                echo "Success"
    failure-command:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
            - run: echo "Failed"