name: Ninth Workflow
on:
  repository_dispatch:
    types:
        [test]


jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: Event Vars
              run: |
                echo "Title: ${{ github.event.client_payload.titleTest }}"