name: Seventeenth Workflow
on:
  workflow_dispatch:
    inputs:
      title:
        description: "Custom Title"
        type: string
        default: "Testing text Title"
        required: false
jobs:
    call-workflow:
        uses: ./.github/workflows/workflow.yml
        with:
            title: ${{ inputs.title }}
    call-external-workflow:
        uses: avlasova05/workflows/.github/workflows/workflow.yml@main
        secrets:
            PASSWORD: ${{ secrets.PASSWORD }}
