name: Sixth Workflow
on:
  push: 
    branches:
        - main
        - "page/*"
        - "page/**"
        - "!page/blog"
    #tags:
     #   - "v1.*"
      #  - "!1.2.2"
    paths:
        - "**.html" 

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: Event Vars
              run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF