name: Twelfth Workflow
on: [push]

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: My Vars & Secrets
              run: |
                echo '${{ vars.STATUS }}'
                echo '${{ secrets.PASSWORD}}'