name: Reusable Workflow
on:
  workflow_call:
    inputs:
        title:
            description: "Custom Title"
            type: string
            default: "Testing text Title"
            required: false
jobs:
    console-log:
        runs-on: ubuntu-latest
        steps:
            - name: Print Title
              run: echo '${{ inputs.title }}'